---
"apiVersion": "v1"
"kind": "ServiceAccount"
"metadata":
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
---
"apiVersion": "rbac.authorization.k8s.io/v1"
"kind": "ClusterRoleBinding"
"metadata":
  "name": "cni-metrics-helper"
"roleRef":
  "apiGroup": "rbac.authorization.k8s.io"
  "kind": "ClusterRole"
  "name": "cni-metrics-helper"
"subjects":
- "kind": "ServiceAccount"
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
---
"apiVersion": "rbac.authorization.k8s.io/v1"
"kind": "ClusterRole"
"metadata":
  "name": "cni-metrics-helper"
"rules":
- "apiGroups":
  - ""
  "resources":
  - "pods"
  - "pods/proxy"
  "verbs":
  - "list"
  - "watch"
  - "get"
---
"apiVersion": "apps/v1"
"kind": "Deployment"
"metadata":
  "labels":
    "k8s-app": "cni-metrics-helper"
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
"spec":
  "selector":
    "matchLabels":
      "k8s-app": "cni-metrics-helper"
  "template":
    "metadata":
      "labels":
        "k8s-app": "cni-metrics-helper"
    "spec":
      "containers":
      - "env":
        - "name": "AWS_CLUSTER_ID"
          "value": ""
        - "name": "USE_CLOUDWATCH"
          "value": "true"
        "image": "013241004608.dkr.ecr.us-gov-west-1.amazonaws.com/cni-metrics-helper:v1.12.1"
        "name": "cni-metrics-helper"
      "serviceAccountName": "cni-metrics-helper"
...
